### ISSUE TITLE
Question about the blog post

### ISSUE THREAD

**Issue by lukewestby** [discord/sorted_set_nif#29]
Hey folks,

Apologies for the partially off-topic issue here, I just wasn't sure where else to reach out.

In [the article](https://discord.com/blog/using-rust-to-scale-elixir-for-11-million-concurrent-users) the author writes

> using the guarantees of Rust is guaranteed not to crash the VM or leak memory

I was wondering if someone could expand on this or direct me to more information about it. I'm curious because crashing and leaking memory are both things that the Rust compiler is happy to let you do in the general case. I took a look at the Rustler project and I see that they repeat the claim about crashes but they also have several open and closed issues related to crashes as well. I think I might just be confused about terms or the domain that was intended in the writing.

Thank you! And if this is simply the wrong venue for this question and this issue needs to be closed without answer I of course understand.

**Comment by Benjamin-Philip** [comment]
@lukewestby, I recommend that you re-post at [Elixirforum](https://elixirforum.com/) quoting the Rustler use of the phrase.
